debug: false

hikvision:
  enabled: true
  cams:
    myCam:
      address: 192.168.1.69
      https: false
      username: admin
      password: admin1234
      rawTcp: false
    myDoorbell:
      address: 192.168.1.13
      https: false
      username: admin
      password: admin666
      # USE RAW TCP IF HTTP STREAMING DOES NOT WORK
      rawTcp: true

mqtt:
  enabled: true
  username: akhil
  password: "asd123##"
  port: 1883
  server: "182.188.2.6"
  topicroot: camera-alerts

webhooks:
  enabled: false
  items:
    - url: "https://webhook.site/52d57401-0ea3-4e43-80a0-ceb02fba2d1e"
      method: "GET" # DEFAULTS TO POST
      headers:
        - "X-Beep: boop"

      # YOU CAN USE TEMPLATE VARIABLES TO FORM THE URL: .Camera, .Event, .Extra
    - url: "https://example.com/webhooks/{{ .Camera }}/events/{{ .Event }}"
      # YOU CAN ALSO USE TEMPLATE VARIABLES IN THE PAYLOAD BODY!
      # BELOW EXAMPLE DELIVERS RAW EVENT TO THE ENDPOINT
      bodyTemplate: '{{ .Extra }}'

    - url: "https://api.telegram.org/bot121212121:token/sendMessage?chat_id=43434343434&text=hello"

  # SIMPLE SHORTHAND FORM FOR THE SAME STUFF AS ABOVE, WILL PERFORM A POST TO EACH URL
  urls:
    - "https://example.com/camera-webhooks"
    - "https://example.com/another-endpoint"
